{u'stats': {u'scheduled': True, u'totalSplits': 1, u'runningSplits': 0,
            u'cpuTimeMillis': 0, u'queuedSplits': 0, u'processedBytes': 0,
            u'rootStage': {u'totalSplits': 1, u'runningSplits': 0,
                           u'subStages': [
                               {u'totalSplits': 0, u'runningSplits': 0,
                                u'subStages': [], u'cpuTimeMillis': 0,
                                u'queuedSplits': 0, u'processedBytes': 0,
                                u'userTimeMillis': 0, u'state': u'FINISHED',
                                u'completedSplits': 0, u'done': True,
                                u'stageId': u'1', u'nodes': 0,
                                u'processedRows': 0, u'wallTimeMillis': 0}],
                           u'cpuTimeMillis': 0, u'queuedSplits': 0,
                           u'processedBytes': 0, u'userTimeMillis': 0,
                           u'state': u'FINISHED', u'completedSplits': 1,
                           u'done': True, u'stageId': u'0', u'nodes': 1,
                           u'processedRows': 0, u'wallTimeMillis': 0},
            u'userTimeMillis': 0, u'state': u'FINISHED', u'completedSplits': 1,
            u'nodes': 1, u'processedRows': 0, u'wallTimeMillis': 0},
 u'id': u'20160812_172808_27033_rv9qe', u'columns': [{u'typeSignature': {
    u'typeArguments': [], u'rawType': u'varchar', u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'event_id'}, {
                                                         u'typeSignature': {
                                                             u'typeArguments': [],
                                                             u'rawType': u'varchar',
                                                             u'literalArguments': []},
                                                         u'type': u'varchar',
                                                         u'name': u'event_type'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'sub_event_type'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'reservation_id'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'db_accounting_audit_id'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'db_audit_timestamp'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'sequence_number'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'month_id'}, {
                                                         u'typeSignature': {
                                                             u'typeArguments': [],
                                                             u'rawType': u'bigint',
                                                             u'literalArguments': []},
                                                         u'type': u'bigint',
                                                         u'name': u'guest_id'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'host_id'}, {
                                                         u'typeSignature': {
                                                             u'typeArguments': [],
                                                             u'rawType': u'bigint',
                                                             u'literalArguments': []},
                                                         u'type': u'bigint',
                                                         u'name': u'hosting_id'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'guestcurrency'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'guestcurrencyrate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'effective_guest_currency_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'hostcurrency'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'hostcurrencyrate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'effective_host_currency_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'guest_cor'}, {
                                                         u'typeSignature': {
                                                             u'typeArguments': [],
                                                             u'rawType': u'varchar',
                                                             u'literalArguments': []},
                                                         u'type': u'varchar',
                                                         u'name': u'host_cor'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'event_datetime'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'description'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'guest_fee_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'host_fee_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'coupon_savings_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'fx_fee_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'guest_price_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'host_payout_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'guest_vat_taxable_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'guest_vat_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'guest_vat_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'guest_vat_country'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'guest_vat_remittance_currency'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'guest_vat_remittance_currency_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'host_vat_taxable_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'host_vat_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'host_vat_micros'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'host_vat_country'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'host_vat_remittance_currency'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'double',
                                                         u'literalArguments': []},
                                                      u'type': u'double',
                                                      u'name': u'host_vat_remittance_currency_rate'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'coupon_loss_definition_id'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'coupon_loss_department'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'coupon_loss_team'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'coupon_loss_type'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'coupon_loss_reason'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'affiliateid'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'affiliaterevshare'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'bigint',
                                                         u'literalArguments': []},
                                                      u'type': u'bigint',
                                                      u'name': u'affiliaterevshareviahosting'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [],
                                                         u'rawType': u'varchar',
                                                         u'literalArguments': []},
                                                      u'type': u'varchar',
                                                      u'name': u'couponserieslabel'},
                                                     {u'typeSignature': {
                                                         u'typeArguments': [{
                                                                                u'typeArguments': [
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'bigint',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'bigint',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'bigint',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'bigint',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []},
                                                                                    {
                                                                                        u'typeArguments': [],
                                                                                        u'rawType': u'varchar',
                                                                                        u'literalArguments': []}],
                                                                                u'rawType': u'row',
                                                                                u'literalArguments': [
                                                                                    u'tax_type',
                                                                                    u'amount_micros',
                                                                                    u'reservation_tax_items_id',
                                                                                    u'rule_id',
                                                                                    u'currency',
                                                                                    u'imposition_type',
                                                                                    u'imposition_name',
                                                                                    u'jurisdiction_id',
                                                                                    u'jurisdiction_name',
                                                                                    u'jurisdiction_level',
                                                                                    u'remittance_amount',
                                                                                    u'exempt_amount',
                                                                                    u'non_taxable_amount',
                                                                                    u'taxable_amount',
                                                                                    u'currency_rate']}],
                                                         u'rawType': u'array',
                                                         u'literalArguments': []},
                                                      u'type': u"array<row<varchar,bigint,bigint,bigint,varchar,varchar,varchar,bigint,varchar,varchar,varchar,varchar,varchar,varchar,varchar>('tax_type','amount_micros','reservation_tax_items_id','rule_id','currency','imposition_type','imposition_name','jurisdiction_id','jurisdiction_name','jurisdiction_level','remittance_amount','exempt_amount','non_taxable_amount','taxable_amount','currency_rate')>",
                                                      u'name': u'taxes'}, {
                                                         u'typeSignature': {
                                                             u'typeArguments': [],
                                                             u'rawType': u'varchar',
                                                             u'literalArguments': []},
                                                         u'type': u'varchar',
                                                         u'name': u'ds'}],
 u'infoUri': u'http://localhost:3506/v1/query/20160812_172808_27033_rv9qe'}
